<?xml version="1.0" encoding="utf-8" ?>
<RevitPythonShell>
  <SearchPaths>
    <!-- a list of paths to add to the engines search path -->
  </SearchPaths>
  <Variables>
    <!-- a list of string variables to add to the scope -->
  </Variables>
  <Commands>
    <!-- a list of preconfigured commands -->
  </Commands>
  <InitScript>
    <![CDATA[    
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Architecture import *

uidoc = __revit__.ActiveUIDocument
doc = __revit__.ActiveUIDocument.Document
selection = list(__revit__.ActiveUIDocument.Selection.Elements)
    ]]>
  </InitScript>
</RevitPythonShell>